In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame(
    {
        'column 1': [1,2,3,4],
        'column 2': [5,6,7,8],
        'column 3': [9,10,11,12]
    }
)
df

   column 1  column 2  column 3
0         1         5         9
1         2         6        10
2         3         7        11
3         4         8        12

In [6]:
#Here, we find the number of rows and number of columns
#in a DataFrame as an ordered-pair
df.shape

(4, 3)

In [4]:
#Here, we only find the number of rows in a DataFrame
df.shape[0]

4

In [5]:
#Here, we only find the number of columns in a DataFrame
df.shape[1]

3